language: ruby
rvm:
  - 1.9.3
  - 1.9.2
env:
  - DB=postgresql
script: bundle exec rspec spec --profile
before_install: gem install bundler
before_script:
  - psql -c 'create database beech-server_test' -U postgres
  - mv config/database.travis.yml config/database.yml
  - RAILS_ENV=test rake db:migrate

